// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPGManager.Data;

#nullable disable

namespace RPGManager.Migrations
{
    [DbContext(typeof(DndDBContext))]
    partial class DndDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RPGManager.Models.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("WorldId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("RPGManager.Models.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alignment")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("alignment");

                    b.Property<int?>("BaseLocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_location_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BaseLocationId");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("RPGManager.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("region_id");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RPGManager.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int?>("LinkedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("linked_id");

                    b.Property<string>("LinkedType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("RPGManager.Models.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alignment")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("alignment");

                    b.Property<string>("Class")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("class");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("FactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("faction_id");

                    b.Property<int?>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Race")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("race");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("LocationId");

                    b.ToTable("NPC", (string)null);
                });

            modelBuilder.Entity("RPGManager.Models.Npcrelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("NpcId1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("npc_id_1");

                    b.Property<int>("NpcId2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("npc_id_2");

                    b.Property<string>("RelationType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("relation_type");

                    b.HasKey("Id");

                    b.HasIndex("NpcId1");

                    b.HasIndex("NpcId2");

                    b.ToTable("NPCRelations", (string)null);
                });

            modelBuilder.Entity("RPGManager.Models.PinnedNpc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("NpcId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("npc_id");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.HasKey("Id");

                    b.HasIndex("NpcId");

                    b.ToTable("PinnedNpcs");
                });

            modelBuilder.Entity("RPGManager.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_id");

                    b.Property<int?>("QuestGiverId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quest_giver_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("активный")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("QuestGiverId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("RPGManager.Models.QuestNpc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("NpcId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("npc_id");

                    b.Property<int>("QuestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quest_id");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("NpcId");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestNPC", (string)null);
                });

            modelBuilder.Entity("RPGManager.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ContinentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("continent_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("RPGManager.Models.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("RPGManager.Models.Continent", b =>
                {
                    b.HasOne("RPGManager.Models.World", "World")
                        .WithMany("Continents")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("RPGManager.Models.Faction", b =>
                {
                    b.HasOne("RPGManager.Models.Location", "BaseLocation")
                        .WithMany("Factions")
                        .HasForeignKey("BaseLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BaseLocation");
                });

            modelBuilder.Entity("RPGManager.Models.Location", b =>
                {
                    b.HasOne("RPGManager.Models.Region", "Region")
                        .WithMany("Locations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("RPGManager.Models.Npc", b =>
                {
                    b.HasOne("RPGManager.Models.Faction", "Faction")
                        .WithMany("Npcs")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RPGManager.Models.Location", "Location")
                        .WithMany("Npcs")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Faction");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RPGManager.Models.Npcrelation", b =>
                {
                    b.HasOne("RPGManager.Models.Npc", "NpcId1Navigation")
                        .WithMany("NpcrelationNpcId1Navigations")
                        .HasForeignKey("NpcId1")
                        .IsRequired();

                    b.HasOne("RPGManager.Models.Npc", "NpcId2Navigation")
                        .WithMany("NpcrelationNpcId2Navigations")
                        .HasForeignKey("NpcId2")
                        .IsRequired();

                    b.Navigation("NpcId1Navigation");

                    b.Navigation("NpcId2Navigation");
                });

            modelBuilder.Entity("RPGManager.Models.PinnedNpc", b =>
                {
                    b.HasOne("RPGManager.Models.Npc", "Npc")
                        .WithMany("PinnedNpcs")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("RPGManager.Models.Quest", b =>
                {
                    b.HasOne("RPGManager.Models.Location", "Location")
                        .WithMany("Quests")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RPGManager.Models.Npc", "QuestGiver")
                        .WithMany("Quests")
                        .HasForeignKey("QuestGiverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("QuestGiver");
                });

            modelBuilder.Entity("RPGManager.Models.QuestNpc", b =>
                {
                    b.HasOne("RPGManager.Models.Npc", "Npc")
                        .WithMany("QuestNpcs")
                        .HasForeignKey("NpcId")
                        .IsRequired();

                    b.HasOne("RPGManager.Models.Quest", "Quest")
                        .WithMany("QuestNpcs")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("RPGManager.Models.Region", b =>
                {
                    b.HasOne("RPGManager.Models.Continent", "Continent")
                        .WithMany("Regions")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("RPGManager.Models.Continent", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("RPGManager.Models.Faction", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("RPGManager.Models.Location", b =>
                {
                    b.Navigation("Factions");

                    b.Navigation("Npcs");

                    b.Navigation("Quests");
                });

            modelBuilder.Entity("RPGManager.Models.Npc", b =>
                {
                    b.Navigation("NpcrelationNpcId1Navigations");

                    b.Navigation("NpcrelationNpcId2Navigations");

                    b.Navigation("PinnedNpcs");

                    b.Navigation("QuestNpcs");

                    b.Navigation("Quests");
                });

            modelBuilder.Entity("RPGManager.Models.Quest", b =>
                {
                    b.Navigation("QuestNpcs");
                });

            modelBuilder.Entity("RPGManager.Models.Region", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("RPGManager.Models.World", b =>
                {
                    b.Navigation("Continents");
                });
#pragma warning restore 612, 618
        }
    }
}
